# Generated by Django 3.1.6 on 2021-02-09 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='imgae',
            new_name='image',
        ),
    ]
