# Generated by Django 3.1.6 on 2021-02-09 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20210209_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='image1',
            new_name='imgae',
        ),
    ]
